### ISSUE TITLE
Numerical Issue in NLP Tests

### ISSUE THREAD

**Issue by ccoffrin** [jump-dev/MINLPTests.jl#16]
One of the NLP tests results in Ipopt hanging indefinitely (with both objective and dual values reporting NaN in the logs), when using Ipopt version 3.12.4, running with linear solver ma27.  This does not seem to be an issue the version distributed by BinaryProvider.

The exact test has not been identified because it is difficult to track which test is being run before the hang.  Adding a debug mode to the these tests would be helpful.

**Comment by odow** [comment]
Is this still a problem? `CTRL+C` should interrupt and show what test failed. Although adding a debug option which printed the name of each test would be useful.
