### ISSUE TITLE
Periodic function in nlp-expr/001_010 implies infinitely many global minimizers

### ISSUE THREAD

**Issue by cvanaret** [jump-dev/MINLPTests.jl#50]
The instance `nlp-expr/001_010` contains the periodic `cos(y)`, `y` free, in its objective.
This means that any point `(-1, pi + 2k pi, 1)` is a global solution.
https://github.com/jump-dev/MINLPTests.jl/blob/46ce8977917c28487bc5da9095f969022a7fa0f8/src/nlp-expr/001_010.jl#L32

An SQP method may converge towards `y = pi` from the starting point, but a trust-region SLP method (that captures no curvature) may travel a bit and get `y = 3pi`.

**Comment by ccoffrin** [comment]
I am open to changing the test to resolve this issue.  Let's hear what @odow thinks as well.

**Comment by odow** [comment]
This example proved challenging for Gurobi as well. Maybe we should just bound `y`.
