### ISSUE TITLE
nlp-expr/003_014.jl and nlp-expr/003_015.jl are identical

### ISSUE THREAD

**Issue by cvanaret** [jump-dev/MINLPTests.jl#51]

**Comment by ccoffrin** [comment]
I think this is a bug in the test. The comments suggest that 003_015 should be using `@NLobjective` instead of `@objective`. However, if that does not make sense, then I agree one these tests can be removed.

CC @odow

**Comment by odow** [comment]
They were different in https://github.com/jump-dev/MINLPTests.jl/blob/master/src/nlp/003_014.jl and https://github.com/jump-dev/MINLPTests.jl/blob/master/src/nlp/003_015.jl.

When I updated them all to use the new nonlinear interface I didn't audit for unneeded tests. 

We can remove`_015`, but having a duplicate isn't the end of the world.
